name: Build and upload to PyPI

on:
  push:

jobs:
  make_sdist:
    name: Make SDist
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install deps
      run: python -m pip install build twine "cython~=3.0.10"
    - name: Generate *.c from *.pyx
      run: python -m cython -3 **/*.pyx
    - name: Build SDist
      run: CYTHONIZE=0 python -m build --sdist
    - uses: actions/upload-artifact@v4
      with:
        name: fatfs-dist
        path: dist/*.tar.gz
        overwrite: true
    - name: Check metadata
      run: twine check dist/*

  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.19.2
        env:
          CIBW_ARCHS_MACOS: x86_64 arm64
          CIBW_BEFORE_BUILD: pip install "cython~=3.0.10"
          CIBW_ENVIRONMENT: CYTHONIZE=1
          CIBW_ENVIRONMENT_PASS_LINUX: CYTHONIZE
          CIBW_SKIP: "*-win32"
      - uses: actions/upload-artifact@v4
        with:
          name: fatfs-dist-${{ matrix.os }}
          path: wheelhouse/*.whl

  upload_to_pypi:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [build_wheels, make_sdist]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v4
      with:
        pattern: fatfs-dist-*
        merge-multiple: true
        path: dist
    - uses: pypa/gh-action-pypi-publish@v1.5.0
      with:
        user: __token__
        password: ${{ secrets.pypi_token }}
        # uncomment for testing
        # repository_url: https://test.pypi.org/legacy/
